What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

#Creating Numpy Arrays

In [1]:
#np.array: function
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [2]:
#2D and 3D
#1D called vector
#2D called matrix
b = np.array([[1,3,4,5], [1,2,6,8]])
print(b)

[[1 3 4 5]
 [1 2 6 8]]


In [3]:
c = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(c) #3D : Tensor

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
#dtype: we can make array of any data type
np.array([1,2,3], dtype=float)
np.array([1,2,3], dtype=bool)
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [5]:
#np.arange
np.arange(1,12)
np.arange(1,  12, 2)

array([ 1,  3,  5,  7,  9, 11])

In [6]:
#reshape: changes given numpy array to diff shape
np.arange(1,11).reshape(2,5)  #2 rows and 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
#np.ones : numpy array with all ones value
np.ones((3,4))   #use case: to give initial weights in neural ntw

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
#np.zeros: np array with all zeroes values
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#np.random
np.random.random((3,4))

array([[0.75377696, 0.0168104 , 0.23191366, 0.51558288],
       [0.9629829 , 0.61852033, 0.00569975, 0.45254072],
       [0.35120741, 0.43758026, 0.66363191, 0.97256898]])

In [10]:
#np.linspace : generates items having same inbetween distance
np.linspace(-10,10,10, dtype=int)
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
#np.identity : diagram items 1
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [12]:
a1 = np.arange(10) #vector
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a2 = np.arange(12, dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [14]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
#ndim : counts the no of dimensions of the given array
a1.ndim
a2.ndim
a3.ndim

3

In [16]:
#shape
a1.shape


(10,)

In [17]:
a3.shape

(2, 2, 2)

there 2 , 2d arrays of shape 2,2

In [18]:
a2.shape

(3, 4)

In [19]:
#size: total no of items
a3.size

8

In [20]:
#itemsize
a1.itemsize

8

In [21]:
a3.itemsize

8

In [22]:
#dtype : shows data types of the items
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


#changing data type

In [23]:
#astype
#changing datatypes
a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

#Array Operations

In [24]:
a1 = np.arange(12,).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [25]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
#Scalar Operation : All arithemetic operations we can perform on an array
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [28]:
#relational
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
#vector operation: an operation which we perform on 2 arrays of np
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [30]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [31]:
#arithmetic
a1 + a2


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

#Array Functions

In [32]:
import numpy as np
a1 = np.random.random((3, 3))
a1 = np.round(a1*100)
a1

array([[72.,  1., 77.],
       [85., 87., 40.],
       [70., 47., 52.]])

In [33]:
#max/min/sum/prod
np.min(a1)
np.max(a1)
np.sum(a1)
np.prod(a1)

np.float64(280556692416000.0)

In [34]:
np.sum(a1)

np.float64(531.0)

In [35]:
np.max(a1)

np.float64(87.0)

In [36]:
#to accesss column wise and row wise min max sum and prod
#0 -> col, and #1 -> row
np.max(a1, axis=0)
np.max(a1, axis=1)

array([77., 87., 70.])

In [37]:
np.prod(a1, axis=0)
np.prod(a1, axis=1)

array([  5544., 295800., 171080.])

In [38]:
#mean , median, std, var

In [39]:
np.mean(a1, axis=0)
np.mean(a1)

np.float64(59.0)

In [40]:
#trignometric functions
np.sin(a1)

array([[ 0.25382336,  0.84147098,  0.99952016],
       [-0.17607562, -0.82181784,  0.74511316],
       [ 0.77389068,  0.12357312,  0.98662759]])

In [41]:
#dot product
#condition : 3,4 and 4, 3 resultant matrix : (3,3): pehele wale row dusre waale ka column match hona chahiye.

In [42]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [43]:
# log and exponents
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [44]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[61., 55., 66.],
       [55., 86.,  1.]])

**Indexing and Slicing**

In [45]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [46]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2[1,0]

np.int64(4)

In [49]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [50]:
a3[1,0,1]

np.int64(5)

In [51]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a1[2:5:2]

array([2, 4])

In [53]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [55]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [56]:
a2[1,::3]

array([4, 7])

In [57]:
a2[0,:]

array([0, 1, 2, 3])

In [58]:
a2[:,2]

array([ 2,  6, 10])

In [59]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [60]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [61]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [62]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [63]:
a3[0,1,:]

array([3, 4, 5])

Iterating

In [64]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [65]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [67]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [68]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping

In [69]:
# reshape
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [70]:
# ravel: converts any dimensional array into 1D
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#Stacking

In [71]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [73]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#Splitting

In [74]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
#np.hsplit(a4,5)

In [76]:
# vertical splitting

In [77]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
#np.vsplit(a5,2)